<h1>Table of Contents<span class="tocSkip"></span></h1>
<div class="toc"><ul class="toc-item"><li><span><a href="#前向神经网络的多种实现方式" data-toc-modified-id="前向神经网络的多种实现方式-1"><span class="toc-item-num">1&nbsp;&nbsp;</span>前向神经网络的多种实现方式</a></span><ul class="toc-item"><li><span><a href="#张量实现方式" data-toc-modified-id="张量实现方式-1.1"><span class="toc-item-num">1.1&nbsp;&nbsp;</span>张量实现方式</a></span></li><li><span><a href="#层实现方式" data-toc-modified-id="层实现方式-1.2"><span class="toc-item-num">1.2&nbsp;&nbsp;</span>层实现方式</a></span></li><li><span><a href="#顺序序列实现" data-toc-modified-id="顺序序列实现-1.3"><span class="toc-item-num">1.3&nbsp;&nbsp;</span>顺序序列实现</a></span></li></ul></li></ul></div>

# 前向神经网络的多种实现方式

In [2]:
import tensorflow as tf 
import numpy as np 

## 张量实现方式

In [7]:
# 定义神经网络各层结构

# 第一层隐藏层
W1 = tf.Variable(tf.random.truncated_normal([784, 256], stddev=0.1))
b1 = tf.Variable(tf.zeros([256]))
# 第二层隐藏成
W2 = tf.Variable(tf.random.truncated_normal([256, 128], stddev=0.1))
b2 = tf.Variable(tf.zeros([128]))
# 第三层 隐藏层
W3 = tf.Variable(tf.random.truncated_normal([128, 64], stddev=0.1))
b3 = tf.Variable(tf.zeros([64]))
# 输出层
W4 = tf.Variable(tf.random.truncated_normal([64, 10], stddev=0.1))
b4 = tf.Variable(tf.zeros([10]))

In [11]:
x = tf.random.normal([4,28*28])

# 自动求导计算
with tf.GradientTape() as tape:
    # x :[b, 28*28]
    # 第一隐藏层前向计算
    h1 = x@W1 + tf.broadcast_to(b1, [x.shape[0], 256])
    h1 = tf.nn.relu(h1)
    # 第二隐藏层前向计算
    h2 = tf.nn.relu(h1@W2+b2)
    # 第三层隐藏层前向计算
    h3 = tf.nn.relu(h2@W3+b3)
    # 第四层隐藏层前向计算
    h4 = h3@W4+b4

In [21]:
h4.numpy

<bound method _EagerTensorBase.numpy of <tf.Tensor: id=441, shape=(4, 10), dtype=float32, numpy=
array([[ 1.2678214 , -1.308991  ,  0.23424053,  0.504708  ,  0.51373863,
        -0.4769796 , -0.01583008,  0.15147185,  0.0100593 ,  0.22782858],
       [ 1.0107487 , -0.02608913,  0.5736121 ,  0.6152973 , -0.8780317 ,
        -0.3283932 , -0.4608319 , -0.7240166 , -0.22022906, -0.3278438 ],
       [ 1.0822912 ,  0.32298836,  0.27799514,  0.7650468 , -0.70618874,
        -0.18008566, -0.78197   , -1.5144409 ,  0.15408808, -0.11194636],
       [ 1.1351967 , -0.13325204,  1.051617  ,  0.03053641,  0.01449656,
        -0.48319286, -0.03912136, -0.77672446,  0.29247746,  0.4701192 ]],
      dtype=float32)>>

## 层实现方式

In [16]:
from tensorflow.keras import layers, Sequential

In [18]:
# 定义各个隐藏层及其参数
fc1 = layers.Dense(256, activation=tf.nn.relu)
fc2 = layers.Dense(128, activation=tf.nn.relu)
fc3 = layers.Dense(64, activation=tf.nn.relu)
fc4 = layers.Dense(10, activation=None)

# 进行运算
x = tf.random.normal([4, 28*28])
h1 = fc1(x)
h2 = fc2(h1)
h3 = fc3(h2)
h4 = fc4(h3)

In [22]:
h4.numpy

<bound method _EagerTensorBase.numpy of <tf.Tensor: id=441, shape=(4, 10), dtype=float32, numpy=
array([[ 1.2678214 , -1.308991  ,  0.23424053,  0.504708  ,  0.51373863,
        -0.4769796 , -0.01583008,  0.15147185,  0.0100593 ,  0.22782858],
       [ 1.0107487 , -0.02608913,  0.5736121 ,  0.6152973 , -0.8780317 ,
        -0.3283932 , -0.4608319 , -0.7240166 , -0.22022906, -0.3278438 ],
       [ 1.0822912 ,  0.32298836,  0.27799514,  0.7650468 , -0.70618874,
        -0.18008566, -0.78197   , -1.5144409 ,  0.15408808, -0.11194636],
       [ 1.1351967 , -0.13325204,  1.051617  ,  0.03053641,  0.01449656,
        -0.48319286, -0.03912136, -0.77672446,  0.29247746,  0.4701192 ]],
      dtype=float32)>>

## 顺序序列实现

In [20]:
x = tf.random.normal([4, 28*28])
model = Sequential([
    layers.Dense(256, activation=tf.nn.relu),
    layers.Dense(128, activation=tf.nn.relu),
    layers.Dense(64, activation=tf.nn.relu),
    layers.Dense(10, activation=None)
])

out = model(x)

In [23]:
out.numpy

<bound method _EagerTensorBase.numpy of <tf.Tensor: id=565, shape=(4, 10), dtype=float32, numpy=
array([[-0.7161818 ,  0.37705937, -1.7789481 ,  0.7740485 ,  0.05857381,
         1.3094213 , -2.140437  ,  0.11440559, -0.99368405,  1.1898942 ],
       [ 0.07335618,  0.21551695, -0.7707263 , -0.8033088 , -0.79920614,
         0.8159759 , -1.4025853 ,  0.5812639 , -1.3767462 ,  1.3988807 ],
       [ 0.3471176 ,  0.7293081 , -1.1671902 ,  0.3643118 ,  0.22588669,
        -0.41095066, -1.6315902 ,  0.60152817, -1.2400624 ,  0.67305744],
       [-0.5959522 ,  0.8720915 , -0.9636747 ,  0.29036406, -0.5421654 ,
         0.85903156, -1.6397976 ,  0.88063675, -0.7481228 ,  1.1595653 ]],
      dtype=float32)>>